version: "3.8"

services:
  #   # Laravel app
  #   app:
  #     image: php:8.0-fpm
  #     container_name: laravel_app
  #     working_dir: /var/www
  #     volumes:
  #       - ./:/var/www
  #       - ./php.ini:/usr/local/etc/php/php.ini
  #     networks:
  #       - app-network

  #   # Nginx web server
  #   webserver:
  #     image: nginx:alpine
  #     container_name: laravel_webserver
  #     working_dir: /var/www
  #     volumes:
  #       - ./:/var/www
  #       - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     ports:
  #       - "80:80"
  #     networks:
  #       - app-network

  # MySQL database
  db:
    image: mariadb:10.8.3
    container_name: blog_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Adminer (Database management)
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
